# -*- coding: utf-8 -*-
"""섬 연결하기

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cwXF6PRvOOKv3sTl78PDgMihgOUgXT6G
"""

def solution(n, costs):
    costs.sort(key=lambda x: x[2])


    connected_islands = {costs[0][0], costs[0][1]}
    total_cost = costs[0][2]

    while len(connected_islands) < n:
        for i in range(1, len(costs)):
            u, v, cost = costs[i]

            if u in connected_islands and v in connected_islands:
                continue

            if u in connected_islands or v in connected_islands:
                connected_islands.update([u, v])
                total_cost += cost
                break

    return total_cost