# -*- coding: utf-8 -*-
"""조이스틱

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cwXF6PRvOOKv3sTl78PDgMihgOUgXT6G
"""

def solution(name):
    spell_move = 0
    for char in name:
        spell_move += min(ord(char) - ord('A'), ord('Z') - ord(char) + 1)

    n = len(name)
    cursor_move = n - 1

    for i in range(n):
        next_i = i + 1
        while next_i < n and name[next_i] == 'A':
            next_i += 1


        distance = min(i + i + n - next_i, (n - next_i) * 2 + i)
        cursor_move = min(cursor_move, distance)

    return spell_move + cursor_move