# -*- coding: utf-8 -*-
"""체육복

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cwXF6PRvOOKv3sTl78PDgMihgOUgXT6G
"""

def solution(n, lost, reserve):
    actual_reserve = set(reserve) - set(lost)
    actual_lost = set(lost) - set(reserve)

    for r in sorted(actual_reserve):
        if r - 1 in actual_lost:
            actual_lost.remove(r - 1)
        elif r + 1 in actual_lost:
            actual_lost.remove(r + 1)

    return n - len(actual_lost)