# -*- coding: utf-8 -*-
"""큰 수 만들기

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cwXF6PRvOOKv3sTl78PDgMihgOUgXT6G
"""

def solution(number, k):
    stack = []

    for num in number:
        while stack and k > 0 and stack[-1] < num:
            stack.pop()
            k -= 1

        stack.append(num)


    if k > 0:
        stack = stack[:-k]

    return "".join(stack)